db.locations.insert([
  {
    address: "6220 Avenue U",
    zipcode: "NY 11234",
    borough: "Brooklyn",
    cuisine: "Cafe",
    grade: "A",
    name: "The Roasted Bean",
    on_wishlist: [],
    location_id: "56018",
  },
  {
    address: "405 Lexington Avenue",
    zipcode: "NY 10174",
    borough: "Manhattan",
    cuisine: "American",
    grade: "A",
    name: "The Diner At The Corner",
    on_wishlist: [],
    location_id: "63426",
  },
  {
    address: "123 Main Street",
    zipcode: "CA 90210",
    borough: "Los Angeles",
    cuisine: "Italian",
    grade: "B",
    name: "Mamma Mia's",
    on_wishlist: [],
    location_id: "98765",
  },
  {
    address: "7th & Pine",
    zipcode: "WA 98101",
    borough: "Seattle",
    cuisine: "Asian Fusion",
    grade: "A",
    name: "Dragonfly",
    on_wishlist: [],
    location_id: "12345",
  },
  {
    address: "555 Elm Street",
    zipcode: "TX 78701",
    borough: "Austin",
    cuisine: "Tex-Mex",
    grade: "B+",
    name: "El Fuego",
    on_wishlist: [],
    location_id: "34567",
  },
  {
    address: "800 Beach Drive",
    zipcode: "FL 33139",
    borough: "Miami",
    cuisine: "Seafood",
    grade: "A",
    name: "Ocean View",
    on_wishlist: [],
    location_id: "78901",
  },
  {
    address: "1600 Market Street",
    zipcode: "PA 19103",
    borough: "Philadelphia",
    cuisine: "Cheesesteak",
    grade: "A+",
    name: "Pat's King of Steaks",
    on_wishlist: [],
    location_id: "23456",
  },
]);
